#!/usr/bin/env bash
# Displays "Best Shool" 10 times using while loop.
# On the 9th iteration , displays "Hi"before "Best Shool".

count=0

while [ $count -lt 9 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best Shool"
	(( count++ ))
done
