#!/usr/bin/env bash
# Displays information about file 'School".

if [ -e "school" ]
then
	echo "school file is not empty"
	else
		echo "shool file is empty"
	fi
	if [ -f "school" ]
	then
		echo "school is regular file"
	fi
else
	echo "school file does not exist"
fi
